[config]
datafiles = ["../data/*.dat"]
infer_schema_length = 5000

[rois.time_general]
type = "time"
filename = "../project_files/rois/test_time_1.csv"

[rois.time_specific]
type = "time"
filename = "../project_files/rois/test_time_2.csv"

[rois.space]
type = "space"
filename = "../project_files/rois/test_space_roi.csv"

[rois.column]
type = "column"
columnname = "CriticalEventStatus"

[metrics.meanVelocity]
function = "colMean"
var = "Velocity"

[metrics.meanLonAccel]
function = "colMean"
var = "LonAccel"

[metrics.meanLatAccel]
function = "colMean"
var = "LatAccel"

[metrics.meanHeadwayDistance]
function = "colMean"
var = "HeadwayDistance"

[metrics.meanHeadwayTime]
function = "colMean"
var = "HeadwayTime"

[metrics.meanLaneOffset]
function = "colMean"
var = "LaneOffset"

[metrics.meanRoadOffset]
function = "colMean"
var = "RoadOffset"

[metrics.meanSteer]
function = "colMean"
var = "Steer"

[metrics.meanHeadPitch]
function = "colMean"
var = "HeadPitch"

[metrics.meanGazePitch]
function = "colMean"
var = "GAZE_PITCH"
